name: build
on: [push]


jobs:
  conda:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}

      - name: Set up conda
        uses: goanpeca/setup-miniconda@v2
        with:
          python-version: 3.8
          activate-environment: citycatio
          environment-file: environment.yml
          use-only-tar-bz2: true

      - name: run tests
        run: python -m unittest discover
        shell: bash -l {0}

      - name: build
        run: python setup.py sdist bdist_wheel
        shell: bash -l {0}

      - name: publish
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          pip install setuptools wheel twine
          twine upload dist/*
        shell: bash -l {0}
